See commits
FlagBrew/FlagBot pull request #14
Opened 2019-01-06 22:36 UTC by GriffinG1

2019-01-10 21:35 UTC, BernardoGiordano requested changes

2019-01-10 21:35 UTC, BernardoGiordano commented on addons/info.py
> +    @commands.command(aliases=['readthedocs', 'docs', 'readthefuckingdocsohmygodjustreadthem'])
is this really necessary?

2019-01-10 21:35 UTC, BernardoGiordano commented on addons/mod.py
> +            reason += "\n\nAction done by {} (This is to deal with audit log scraping".format(ctx.author)
Add missing `)`

2019-01-10 23:08 UTC, GriffinG1 commented on addons/info.py
> +    @commands.command(aliases=['readthedocs', 'docs', 'readthefuckingdocsohmygodjustreadthem'])
You really don’t find it funny?

2019-01-11 06:24 UTC, BernardoGiordano approved these changes

2019-01-11 06:24 UTC, merged